version: '3.8'

services:
  document-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document-microservice
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - DISPLAY=:99
      - PORT=${PORT:-8080}
      - API_KEY=${API_KEY:-}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Resource limits to prevent Chrome from consuming too much memory
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
    # Security options
    security_opt:
      - no-new-privileges:true
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: pdf-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - DOCUMENT_SERVICE_PORT=${PORT:-8080}
    depends_on:
      - document-microservice
    restart: unless-stopped
    profiles:
      - with-nginx

networks:
  default:
    name: document-network